name: Manual Inputs
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Environment
        default: dev-env
        required: true
      BRANCH:
        description: 'Branch to use'
        required: true
        default: 'dev'
        
jobs:
  bump-version:
    name: Bump Package Versio
    runs-on: ubuntu-latest
    steps:
      - name: Example variable usag
        run: git tag ${{ github.event.inputs.version }}
